---
title: "ECCO5445SU22: Assignment05"
author: "Francis Surroca"
date: '2022-07-17'
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Question 2 from Assignment02
```{r}
intTwo = 2
floatTwo = 2.0
mixed = 10j
aString = "2 Cool for School"
aBool = TRUE

print(typeof(intTwo))
print(typeof(floatTwo))
print(typeof(mixed))
print(typeof(aString))
print(typeof(aBool))
```

# Question 5 from Assignment02
```{r}
foobar <- function(value) {
  if (value %% 15 == 0) {
    result <- "foobar"
  } else if (value %% 3 == 0){
    result <- "foo"
  } else if (value %% 5 == 0) {
    result <- "bar"
  } else {
    result <- "Not a multiple of 3, 5, or 15"
  }

  return(result)
}

foobar
foobar(5)
foobar(3)
foobar(15)
foobar(60)
foobar(-5)
```
# Question 3
```{r}
attach(swiss)
summary(swiss)
detach(swiss)
```
# Question 4
```{r}
attach(swiss)
ordered <- swiss[order(swiss$Agriculture), ]
ordered
View(ordered)
```

Looking at the ordered on Agriculture data frame, we can see that Herens province has the highest percent of males involved in agriculture.

```{r}
swiss[which.max(swiss$Agriculture),]
detach(swiss)
```

We can also use switch.max to extract the row with the max of the agriculture column which we see again is Herens.

# Question 5
List the correlations

```{r}
attach(swiss)
cor(swiss)
detach(swiss)
```